### ISSUE TITLE
[BUG] Error in Bazarr using docker compose

### ISSUE THREAD

**Issue by kuesttman** [linuxserver/docker-bazarr#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm running several docker containers using Portainer, sonarr, radarr, prowlarr, all working perfectly. I went to install the bazarr to use and it did not start. There was an error in the container.

### Expected Behavior

.

### Steps To Reproduce

.

### Environment

```markdown
- OS:UBUNTU 22.04 LTS
- How docker service was installed: gerenciador de pacotes da distro
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1002
      - PGID=1003
      - TZ=Brazil
    volumes:
      - /media/docker/bazarr/config:/config
      - /media/drive/:/media/
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.bazarr.entrypoints=websecure
      - traefik.http.routers.bazarr.rule=Host(`bazarr.meusite.com`)
    networks:
      - proxy      
    ports:
      - 6767:6767
    restart: unless-stopped
    
networks:
  proxy:
    external: true
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1002
User gid:    1003
-------------------------------------
[custom-init] No custom files found, skipping...
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/waitress/adjustments.py", line 374, in __init__
    for s in socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -8] Unrecognized service
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 41, in <module>
    from app.server import webserver  # noqa E402
  File "/app/bazarr/bin/bazarr/app/server.py", line 111, in <module>
    webserver = Server()
  File "/app/bazarr/bin/bazarr/app/server.py", line 43, in __init__
    self.configure_server()
  File "/app/bazarr/bin/bazarr/app/server.py", line 47, in configure_server
    self.server = create_server(app,
  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 49, in create_server
    adj = Adjustments(**kw)
  File "/app/bazarr/bin/bazarr/../libs/waitress/adjustments.py", line 401, in __init__
    raise ValueError("Invalid host/port specified.")
ValueError: Invalid host/port specified.
```

**Comment by Roxedus** [comment]
Brazil is not a valid timezone

**Comment by kuesttman** [comment]
I understand, I changed it, I put timezone america/sao_paulo and the same problem continued.

**Comment by aptalca** [comment]
https://wikipedia.org/wiki/List_of_tz_database_time_zones
