### ISSUE TITLE
[BUG] No module named 'pkg_resources' from v.1.2.4-ls207 and afterwards on QNAP

### ISSUE THREAD

**Issue by T81** [linuxserver/docker-bazarr#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

App does not start due to "ModuleNotFoundError"

### Steps To Reproduce

Deploy container on a QNAP

### Environment

```markdown
- OS: QNAP
- How docker service was installed: cli
```

### CPU architecture

x86-64

### Docker creation

```bash
Using the linuxservio compose file contents
```

### Container logs

```bash
[custom-init] No custom files found, skipping...
Bazarr starting...
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 20, in <module>
    from app.check_update import apply_update, check_releases, check_if_new_update  # noqa E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/app/check_update.py", line 14, in <module>
    from .config import settings
  File "/app/bazarr/bin/bazarr/app/config.py", line 8, in <module>
    from subliminal.cache import region
  File "/app/bazarr/bin/bazarr/../libs/subliminal/__init__.py", line 12, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/app/bazarr/bin/bazarr/../libs/subliminal/core.py", line 29, in <module>
    from babelfish import Language, LanguageReverseError
  File "/app/bazarr/bin/bazarr/../libs/babelfish/__init__.py", line 14, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "/app/bazarr/bin/bazarr/../libs/babelfish/converters/__init__.py", line 5, in <module>
    from pkg_resources import iter_entry_points, EntryPoint
ModuleNotFoundError: No module named 'pkg_resources'
Bazarr exited.
```

**Comment by j0nnymoe** [comment]
I suspect you're experiencing the same as portainer and Synology GUI's: https://info.linuxserver.io/issues/2023-05-22-portainer/

**Comment by Roxedus** [comment]
Most likely this https://info.linuxserver.io/issues/2023-05-22-portainer/

**Comment by T81** [comment]
Everything else, that is, 14 containers are all working fine except when updating bazarr. I am using portainer for management. This has happened when the image rebased to Alpine, maybe this is causing the issue. It looks more than a coincidence

**Comment by thespad** [comment]
That's our recommendation, otherwise you can completely remove it from Portainer and redeploy, rather than doing a recreate/update, which will work around the issue.

**Comment by T81** [comment]
Redeploying outside portainer solved the issue

**Comment by jb773** [comment]
For anyone who wants an actual solution other than unwinding their whole Portainer setup, I had some success with (1) removing/deleting everything Bazarr including the downloaded images, volumes, etc, and (2) taking out the environment variables for PATH, HOME, TERM from my docker-compose stack in Portainer. Redeployed the stack and it works fine for now.
