### ISSUE TITLE
[BUG] Update to latest development release

### ISSUE THREAD

**Issue by nismanoku** [linuxserver/docker-bazarr#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Get an error in the logs and bazarr keeps exciting and starting

### Expected Behavior

Config.ini should be converted to Config.yaml

### Steps To Reproduce

1. Unraid docker
2.  Update container with 

### Environment

```markdown
- OS: Unraid 6.12.4
- How docker service was installed: Unraid docker service
- For now reverted to using 'lscr.io/linuxserver/bazarr:development-version-v1.3.1' as this works
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='bazarr-dev'
  --net='eth1.3'
  --ip='xx.xx.xx.xx'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="xxxxx"
  -e HOST_CONTAINERNAME="bazarr-dev"
  -e 'TCP_PORT_6767'='6767'
  -e 'PUID'='1011'
  -e 'PGID'='100'
  -e 'UMASK'='002'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:6767]/system/status'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/bazarr-logo.png'
  -v '/mnt/user/Movies/':'/Movies':'rw'
  -v '/mnt/user/Series/':'/Series':'rw'
  -v '/mnt/user/Backup/BazarrDev/':'/Backup':'rw'
  -v '/mnt/cache_nvme/Dockers/bazarr-dev':'/config':'rw' 'lscr.io/linuxserver/bazarr:development'
```

### Container logs

```bash
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 22, in <module>
    from app.check_update import apply_update, check_releases, check_if_new_update  # noqa E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/app/check_update.py", line 15, in <module>
    from .config import settings
  File "/app/bazarr/bin/bazarr/app/config.py", line 355, in <module>
    convert_ini_to_yaml(config_ini_file)
  File "/app/bazarr/bin/bazarr/app/config.py", line 340, in convert_ini_to_yaml
    items = config_object.items(section)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/configparser.py", line 875, in items
    return [(option, value_getter(option)) for option in orig_keys]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/configparser.py", line 875, in <listcomp>
    return [(option, value_getter(option)) for option in orig_keys]
                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/configparser.py", line 871, in <lambda>
    value_getter = lambda option: self._interpolation.before_get(self,
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/configparser.py", line 396, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.11/configparser.py", line 443, in _interpolate_some
    raise InterpolationSyntaxError(
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%'
```

**Comment by Roxedus** [comment]
I would argue the application should handle this migration, it should not be the job of the application packager.

**Comment by nismanoku** [comment]
With the new development release the conversion from config.ini to config.yaml completes without errors.

[development-v1.3.2-beta.2-ls546]
(https://github.com/linuxserver/docker-bazarr/releases/tag/development-v1.3.2-beta.2-ls546) Pre-release

LinuxServer Changes:

Install unrar from [linuxserver repo](https://github.com/linuxserver/docker-unrar).

bazarr Changes:

From newest to oldest:

Fixed config.ini conversion by disabling interpolation with ConfigParser that failed with addic7ed cookie. [85c65ec](https://github.com/morpheus65535/bazarr/commit/85c65ecb5a33497d1a152bbf46412afa2838e211)
