### ISSUE TITLE
Bazaar failing to load and getting timeouts since last update.

### ISSUE THREAD

**Issue by oublie1234** [linuxserver/docker-bazarr#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Docker timing out or not loading, image is starting in unraid but not accessible have to restart docker to get access Errors in logs.

### Expected Behavior

expected to run and be accessible no responsive since last update.

### Steps To Reproduce

Faulty since last update.

### Environment

```markdown
- OS:Unraid 6.12.10
- Installed via unraid apps
```

### CPU architecture

x86-64

### Docker creation

```bash
Standard Install via Unraid apps.
```

### Container logs

```bash
text  error  warn  system  array  login  

/app/bazarr/bin/bazarr/../custom_libs/subzero/language.py:165: SyntaxWarning: invalid escape sequence '\.'
  IETF_MATCH = ".+\.([^-.]+)(?:-[A-Za-z]+)?$"
/app/bazarr/bin/bazarr/../custom_libs/subzero/language.py:166: SyntaxWarning: invalid escape sequence '\.'
  ENDSWITH_LANGUAGECODE_RE = re.compile("\.([^-.]{2,3})(?:-[A-Za-z]{2,})?$")
/app/bazarr/bin/bazarr/../custom_libs/subzero/language.py:170: SyntaxWarning: invalid escape sequence '\.'
  language_match = re.match(".+\.([^\.]+)$" if not ietf
2024-07-07 14:55:56,594 - root                             (15470ad36b28) :  ERROR (check_update:33) - Error trying to get releases from Github. Connection Error.
Connection to localhost (127.0.0.1) 6767 port [tcp/*] succeeded!
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 63, in <module>
    load_language_in_db()
  File "/app/bazarr/bin/bazarr/languages/get_languages.py", line 29, in load_language_in_db
    database.execute(
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/orm/scoping.py", line 778, in execute
    return self._proxied.execute(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/orm/session.py", line 2306, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/orm/session.py", line 2191, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/orm/bulk_persistence.py", line 1596, in orm_execute_statement
    result = _bulk_update(
             ^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/orm/bulk_persistence.py", line 328, in _bulk_update
    persistence._emit_update_statements(
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/orm/persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
        ^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1408, in execute
    return meth(
           ^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/sql/elements.py", line 513, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1630, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 1803, in _execute_context
    conn = self._revalidate_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/sqlalchemy/engine/base.py", line 670, in _revalidate_connection
    raise exc.ResourceClosedError("This Connection is closed")
sqlalchemy.exc.ResourceClosedError: This Connection is closed
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────
Linuxserver.io version: v1.4.3-ls257
Build-date: 2024-07-05T09:37:22+00:00
───────────────────────────────────────
    
[custom-init] No custom files found, skipping...
[ls.io-init] done.

** Press ANY KEY to close this window **
```

**Comment by Roxedus** [comment]
Get the docker run for the container. https://docs.linuxserver.io/general/how-to-get-support/#how-to-get-support

**Comment by wcorybeck** [comment]
> Get the docker run for the container. https://docs.linuxserver.io/general/how-to-get-support/#how-to-get-support

I'm experiencing the same issue. Here is the link to my docker run.

https://gist.github.com/wcorybeck/816b8049d9c731c3a55d9163611f3916

**Comment by super-cooper** [comment]
I'm also experiencing this. Tried pulling the image minutes before posting with no success:

```yaml
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - ./bazarr:/config
      - media:/media
```

This is the config I've had since I started using bazarr a few months ago.

**Comment by super-cooper** [comment]
This issue has definitely not been resolved

**Comment by punteroanull** [comment]
Dunno if it's the same issue, but I'm getting this error on start up, and it doesn't work.

```
[custom-init] No custom files found, skipping...

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'
```
