### ISSUE TITLE
Bazarr linuxserver/bazarr:1.4.3 fails to run

### ISSUE THREAD

**Issue by seemebreakthis** [linuxserver/docker-bazarr#137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Fails to run.  Log shows this:

````
To support LSIO projects visit:

https://www.linuxserver.io/donate/


───────────────────────────────────────

GID/UID

───────────────────────────────────────


User UID:    1035

User GID:    100

───────────────────────────────────────

Linuxserver.io version: v1.4.3-ls258

Build-date: 2024-07-09T21:26:59+00:00

───────────────────────────────────────

    

[custom-init] No custom files found, skipping...

crond[141]: crond (busybox 1.36.1) started, log level 5

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'

````

### Expected Behavior

Bazarr starts with no problem

### Steps To Reproduce

Just start the container and it runs into this error loop without starting successfully.

Seems like the module "disutils" is missing.

I tried to enter the container terminal then ran this command to see if I could workaround this problem:

apt-get install python3-distutils

But apparently the container doesn't have apt-get.

### Environment

```markdown
- OS:  Synology DSM 7.2
- How docker service was installed:  Through portainer (updated image from a previous working version - linuxserver/bazarr:1.4.1
```

### CPU architecture

x86-64

### Docker creation

```bash
Docker Compose:
`
services:
  Bazarr:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    container_name: "Bazarr"

    entrypoint:
      - "/init"

    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$(whoami)@$(hostname):$(pwd)\\$ "
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "TZ=Asia/Hong_Kong"
      - "PYTHONPATH=/lsiopy/lib/python3.12/site-packages"
      - "PUID=1035"
      - "PGID=100"

    expose:
      - "6767/tcp"

    hostname: "7a440ac70693"

    image: "linuxserver/bazarr:1.4.3"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- v1.4.0-ls225 Build-date:- 2023-11-28T12:47:09+00:00"
      maintainer: "chbmb"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2023-11-28T12:47:09+00:00"
      org.opencontainers.image.description: "[Bazarr](https://www.bazarr.media/) is a companion application\
        \ to Sonarr and Radarr. It can manage and download subtitles based on your requirements. You define\
        \ your preferences by TV show or movie and Bazarr takes care of everything for you."
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-bazarr"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "e403f1ffda215b2b04f49b5f0d42de4b83bfb7b5"
      org.opencontainers.image.revision: "e403f1ffda215b2b04f49b5f0d42de4b83bfb7b5"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-bazarr"
      org.opencontainers.image.title: "Bazarr"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-bazarr/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "v1.4.0-ls225"

    logging:
      driver: "db"
      options: {}

    restart: "always"

    stdin_open: true

    tty: true

    volumes:
      - "/volume1/docker/bazarr/config:/config"
      - "/volume1/docker/radarr/movies:/movies"
      - "/volume1/docker/sonarr/data:/data"

    working_dir: "/"

version: "3.6"
````
### Container logs

````
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1035
User GID:    100
───────────────────────────────────────
Linuxserver.io version: v1.4.3-ls258
Build-date: 2024-07-09T21:26:59+00:00
───────────────────────────────────────

[custom-init] No custom files found, skipping...
crond[141]: crond (busybox 1.36.1) started, log level 5
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
````

**Comment by thespad** [comment]
There is no issue with the image, please see https://info.linuxserver.io/issues/2023-05-22-portainer/
