### ISSUE TITLE
[BUG] Bazarr latest does not start

### ISSUE THREAD

**Issue by puthre** [linuxserver/docker-bazarr#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to deploy the latest image using portainer and it does not start. 
This is what I get in the logs:

To support the app dev(s) visit:

Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url

To support LSIO projects visit:

https://www.linuxserver.io/donate/

───────────────────────────────────────

GID/UID

───────────────────────────────────────

User UID:    1000

User GID:    1000

───────────────────────────────────────

Linuxserver.io version: v1.4.5-ls273

Build-date: 2024-10-15T21:27:15+00:00

───────────────────────────────────────

    

[custom-init] No custom files found, skipping...

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

    from bazarr.app.get_args import args

  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>

    from distutils.util import strtobool

ModuleNotFoundError: No module named 'distutils'

### Expected Behavior

Should start

### Steps To Reproduce

In Debian
Tried to start latest container using  portainer
Does not start, errors in logs

### Environment

```markdown
- OS:
Debian
- How docker service was installed:
Portainer
```

### CPU architecture

x86-64

### Docker creation

```bash
used portainer
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
Linuxserver.io version: v1.4.5-ls273
Build-date: 2024-10-15T21:27:15+00:00
───────────────────────────────────────
    
[custom-init] No custom files found, skipping...
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>
    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
```

**Comment by Roxedus** [comment]
It sounds very much like portainers poor handling of variables. https://info.linuxserver.io/issues/2023-05-22-portainer/
Cant know for sure until you post how the container is created in portainer

**Comment by puthre** [comment]
> It sounds very much like portainers poor handling of variables. https://info.linuxserver.io/issues/2023-05-22-portainer/ Cant know for sure until you post how the container is created in portainer

Wow, that was exactly the issue, I didn't even entertain the idea that the containers are not entirely rebuilt. I've redone the container from scratch and all is good now.

**Comment by aptalca** [comment]
Containers are recreated but portainer reads the internal vars from the old container and force sets them externally in the new container, which is one of the many reasons we recommend against portainer.
