### ISSUE TITLE
 AttributeError: \NoneType\ object has no attribute \check\

### ISSUE THREAD

**Issue by jamesking420** [linuxserver/docker-bazarr#15]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
Traceback (most recent call last):
 File "/app/bazarr/bazarr/get_subtitle.py", line 357, in manual_search
  language_hook=None) # fixme
 File "/app/bazarr/bazarr/../libs/subliminal/core.py", line 653, in list_subtitles
  subtitles = pool.list_subtitles(video, languages - video.subtitle_languages)
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 453, in list_subtitles
  itertools.repeat(languages, len(self.providers))):
 File "/app/bazarr/bazarr/../libs/concurrent/futures/_base.py", line 581, in result_iterator
  yield future.result()
 File "/app/bazarr/bazarr/../libs/concurrent/futures/_base.py", line 398, in result
  return self.__get_result()
 File "/app/bazarr/bazarr/../libs/concurrent/futures/thread.py", line 55, in run
  result = self.fn(*self.args, **self.kwargs)
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 437, in list_subtitles_provider
  provider_subtitles = super(SZAsyncProviderPool, self).list_subtitles_provider(provider, video, languages)
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 140, in list_subtitles_provider
  if not provider_registry[provider].check(video):
AttributeError: \NoneType\ object has no attribute \check\
	

QNAP and portainer

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 10-adduser: executing... ,
usermod: no changes,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
We gratefully accept donations at:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    911,
User gid:    911,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
Bazarr starting...,
2019-02-19 16:34:47,035 - root                             (7f0e24eefb88) :  INFO (main:1889) - BAZARR is started and waiting for request on http://0.0.0.0:6767/,
Traceback (most recent call last):,
  File "/app/bazarr/bazarr/../libs/bottle.py", line 862, in _handle,
    return route.call(**args),
  File "/app/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper,
    rv = callback(*a, **ka),
  File "/app/bazarr/bazarr/main.py", line 135, in wrapper,
    return func(*a, **ka),
  File "/app/bazarr/bazarr/main.py", line 1729, in get_subtitle_movie,
    result = download_subtitle(moviePath, language, hi, providers_list, providers_auth, sceneName, title, 'movie'),
  File "/app/bazarr/bazarr/get_subtitle.py", line 247, in download_subtitle,
    language_hook=None)  # fixme,
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 734, in download_best_subtitles,
    subtitles = pool.download_best_subtitles(pool.list_subtitles(video, languages - video.subtitle_languages),,
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 453, in list_subtitles,
    itertools.repeat(languages, len(self.providers))):,
  File "/app/bazarr/bazarr/../libs/concurrent/futures/_base.py", line 581, in result_iterator,
    yield future.result(),
  File "/app/bazarr/bazarr/../libs/concurrent/futures/_base.py", line 398, in result,
    return self.__get_result(),
  File "/app/bazarr/bazarr/../libs/concurrent/futures/thread.py", line 55, in run,
    result = self.fn(*self.args, **self.kwargs),
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 437, in list_subtitles_provider,
    provider_subtitles = super(SZAsyncProviderPool, self).list_subtitles_provider(provider, video, languages),
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 140, in list_subtitles_provider,
    if not provider_registry[provider].check(video):,
AttributeError: 'NoneType' object has no attribute 'check',
Traceback (most recent call last):,
  File "/app/bazarr/bazarr/../libs/bottle.py", line 862, in _handle,
    return route.call(**args),
  File "/app/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper,
    rv = callback(*a, **ka),
  File "/app/bazarr/bazarr/main.py", line 135, in wrapper,
    return func(*a, **ka),
  File "/app/bazarr/bazarr/main.py", line 1729, in get_subtitle_movie,
    result = download_subtitle(moviePath, language, hi, providers_list, providers_auth, sceneName, title, 'movie'),
  File "/app/bazarr/bazarr/get_subtitle.py", line 247, in download_subtitle,
    language_hook=None)  # fixme,
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 734, in download_best_subtitles,
    subtitles = pool.download_best_subtitles(pool.list_subtitles(video, languages - video.subtitle_languages),,
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 453, in list_subtitles,
    itertools.repeat(languages, len(self.providers))):,
  File "/app/bazarr/bazarr/../libs/concurrent/futures/_base.py", line 581, in result_iterator,
    yield future.result(),
  File "/app/bazarr/bazarr/../libs/concurrent/futures/_base.py", line 398, in result,
    return self.__get_result(),
  File "/app/bazarr/bazarr/../libs/concurrent/futures/thread.py", line 55, in run,
    result = self.fn(*self.args, **self.kwargs),
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 437, in list_subtitles_provider,
    provider_subtitles = super(SZAsyncProviderPool, self).list_subtitles_provider(provider, video, languages),
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 140, in list_subtitles_provider,
    if not provider_registry[provider].check(video):,
AttributeError: 'NoneType' object has no attribute 'check',
Traceback (most recent call last):,
  File "/app/bazarr/bazarr/../libs/bottle.py", line 862, in _handle,
    return route.call(**args),
  File "/app/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper,
    rv = callback(*a, **ka),
  File "/app/bazarr/bazarr/main.py", line 135, in wrapper,
    return func(*a, **ka),
  File "/app/bazarr/bazarr/main.py", line 1066, in wanted_search_missing_subtitles_list,
    wanted_search_missing_subtitles(),
  File "/app/bazarr/bazarr/get_subtitle.py", line 660, in wanted_search_missing_subtitles,
    wanted_download_subtitles(episode[0]),
  File "/app/bazarr/bazarr/get_subtitle.py", line 573, in wanted_download_subtitles,
    episode[7], 'series'),
  File "/app/bazarr/bazarr/get_subtitle.py", line 247, in download_subtitle,
    language_hook=None)  # fixme,
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 734, in download_best_subtitles,
    subtitles = pool.download_best_subtitles(pool.list_subtitles(video, languages - video.subtitle_languages),,
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 453, in list_subtitles,
    itertools.repeat(languages, len(self.providers))):,
  File "/app/bazarr/bazarr/../libs/concurrent/futures/_base.py", line 581, in result_iterator,
    yield future.result(),
  File "/app/bazarr/bazarr/../libs/concurrent/futures/_base.py", line 398, in result,
    return self.__get_result(),
  File "/app/bazarr/bazarr/../libs/concurrent/futures/thread.py", line 55, in run,
    result = self.fn(*self.args, **self.kwargs),
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 437, in list_subtitles_provider,
    provider_subtitles = super(SZAsyncProviderPool, self).list_subtitles_provider(provider, video, languages),
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 140, in list_subtitles_provider,
    if not provider_registry[provider].check(video):,
AttributeError: 'NoneType' object has no attribute 'check',
Traceback (most recent call last):,
  File "/app/bazarr/bazarr/../libs/bottle.py", line 862, in _handle,
    return route.call(**args),
  File "/app/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper,
    rv = callback(*a, **ka),
  File "/app/bazarr/bazarr/main.py", line 135, in wrapper,
    return func(*a, **ka),
  File "/app/bazarr/bazarr/main.py", line 1066, in wanted_search_missing_subtitles_list,
    wanted_search_missing_subtitles(),
  File "/app/bazarr/bazarr/get_subtitle.py", line 660, in wanted_search_missing_subtitles,
    wanted_download_subtitles(episode[0]),
  File "/app/bazarr/bazarr/get_subtitle.py", line 573, in wanted_download_subtitles,
    episode[7], 'series'),
  File "/app/bazarr/bazarr/get_subtitle.py", line 247, in download_subtitle,
    language_hook=None)  # fixme,
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 734, in download_best_subtitles,
    subtitles = pool.download_best_subtitles(pool.list_subtitles(video, languages - video.subtitle_languages),,
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 453, in list_subtitles,
    itertools.repeat(languages, len(self.providers))):,
  File "/app/bazarr/bazarr/../libs/concurrent/futures/_base.py", line 581, in result_iterator,
    yield future.result(),
  File "/app/bazarr/bazarr/../libs/concurrent/futures/_base.py", line 398, in result,
    return self.__get_result(),
  File "/app/bazarr/bazarr/../libs/concurrent/futures/thread.py", line 55, in run,
    result = self.fn(*self.args, **self.kwargs),
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 437, in list_subtitles_provider,
    provider_subtitles = super(SZAsyncProviderPool, self).list_subtitles_provider(provider, video, languages),
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 140, in list_subtitles_provider,
    if not provider_registry[provider].check(video):,
AttributeError: 'NoneType' object has no attribute 'check',
Traceback (most recent call last):,
  File "/app/bazarr/bazarr/../libs/bottle.py", line 862, in _handle,
    return route.call(**args),
  File "/app/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper,
    rv = callback(*a, **ka),
  File "/app/bazarr/bazarr/main.py", line 135, in wrapper,
    return func(*a, **ka),
  File "/app/bazarr/bazarr/main.py", line 1729, in get_subtitle_movie,
    result = download_subtitle(moviePath, language, hi, providers_list, providers_auth, sceneName, title, 'movie'),
  File "/app/bazarr/bazarr/get_subtitle.py", line 247, in download_subtitle,
    language_hook=None)  # fixme,
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 734, in download_best_subtitles,
    subtitles = pool.download_best_subtitles(pool.list_subtitles(video, languages - video.subtitle_languages),,
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 453, in list_subtitles,
    itertools.repeat(languages, len(self.providers))):,
  File "/app/bazarr/bazarr/../libs/concurrent/futures/_base.py", line 581, in result_iterator,
    yield future.result(),
  File "/app/bazarr/bazarr/../libs/concurrent/futures/_base.py", line 398, in result,
    return self.__get_result(),
  File "/app/bazarr/bazarr/../libs/concurrent/futures/thread.py", line 55, in run,
    result = self.fn(*self.args, **self.kwargs),
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 437, in list_subtitles_provider,
    provider_subtitles = super(SZAsyncProviderPool, self).list_subtitles_provider(provider, video, languages),
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 140, in list_subtitles_provider,
    if not provider_registry[provider].check(video):,
AttributeError: 'NoneType' object has no attribute 'check',
Traceback (most recent call last):,
  File "/app/bazarr/bazarr/../libs/bottle.py", line 862, in _handle,
    return route.call(**args),
  File "/app/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper,
    rv = callback(*a, **ka),
  File "/app/bazarr/bazarr/main.py", line 135, in wrapper,
    return func(*a, **ka),
  File "/app/bazarr/bazarr/main.py", line 1729, in get_subtitle_movie,
    result = download_subtitle(moviePath, language, hi, providers_list, providers_auth, sceneName, title, 'movie'),
  File "/app/bazarr/bazarr/get_subtitle.py", line 247, in download_subtitle,
    language_hook=None)  # fixme,
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 734, in download_best_subtitles,
    subtitles = pool.download_best_subtitles(pool.list_subtitles(video, languages - video.subtitle_languages),,
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 453, in list_subtitles,
    itertools.repeat(languages, len(self.providers))):,
  File "/app/bazarr/bazarr/../libs/concurrent/futures/_base.py", line 581, in result_iterator,
    yield future.result(),
  File "/app/bazarr/bazarr/../libs/concurrent/futures/_base.py", line 398, in result,
    return self.__get_result(),
  File "/app/bazarr/bazarr/../libs/concurrent/futures/thread.py", line 55, in run,
    result = self.fn(*self.args, **self.kwargs),
##  Thanks, team linuxserver.io

Very happy to provide more info but don't know what you might need.  This error seems to happen with any video.

**Comment by thelamer** [comment]
This is a python exception from the application, I really think you would get better answers from the developers and maintainers of the application: 
https://github.com/morpheus65535/bazarr

If they point you back to us, we can try to dive into your Docker setup and see if anything is misconfigured.

**Comment by homerr** [comment]
Running as ID 911... normal for qnap?

**Comment by jamesking420** [comment]
Thank you. This did indeed turn out to be an application error. I thought it might be docker as I couldn't find any other mention of this application error online, on their GitHub. 

Sorry for bothering you. :-)
