### ISSUE TITLE
HTTP/500 with 'dict' object has no attribute 'code2'

### ISSUE THREAD

**Issue by esticle** [linuxserver/docker-bazarr#31]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Expect the wizard page to load on initial install

## Current Behavior
On a new install, using the v2 docker compose file as template it appears that Bazarr does not start up because /config/log does not exist - once this is manually created and chown'd appropriately the service runs on port 6767 as expected.

Moving on and hitting the port I am getting a HTTP 500 error after the URL rewrites to /wizard 

```
Error: 500 Internal Server Error
Sorry, the requested URL 'http://127.0.0.1:6767/wizard' caused an error:

Internal Server Error
Exception:
AttributeError("'dict' object has no attribute 'code2'",)
Traceback:
Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 122, in wrapper
    return func(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 220, in wizard
    base_url=base_url)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/app/bazarr/views/wizard.tpl", line 114, in <module>
    % include('wizard_subtitles')
  File "/app/bazarr/bazarr/../libs/bottle.py", line 3386, in _include
    return self.cache[_name].execute(env['_stdout'], env)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/app/bazarr/views/wizard_subtitles.tpl", line 108, in <module>
    <option value="{{language.code2}}">{{language.name}}</option>
AttributeError: 'dict' object has no attribute 'code2'
```
docker logs on the container shows much the same:

```
...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Bazarr starting...
2019-11-05 22:06:32,664 - root                             (7f8d528a7d48) :  INFO (init:70) - BAZARR Database created successfully
2019-11-05 22:06:39,488 - root                             (7f8d528a7d48) :  INFO (main:2128) - BAZARR is started and waiting for request on http://0.0.0.0:6767/
Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 122, in wrapper
    return func(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 220, in wizard
    base_url=base_url)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/app/bazarr/views/wizard.tpl", line 114, in <module>
    % include('wizard_subtitles')
  File "/app/bazarr/bazarr/../libs/bottle.py", line 3386, in _include
    return self.cache[_name].execute(env['_stdout'], env)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/app/bazarr/views/wizard_subtitles.tpl", line 108, in <module>
    <option value="{{language.code2}}">{{language.name}}</option>
AttributeError: 'dict' object has no attribute 'code2'

```

## Steps to Reproduce

1. docker-compose -f bazarr.yaml up -d
2. docker logs bazarr -f
3. curl http://localhost:6767/wizard

## Environment
**OS:**      Ubuntu 16.04
**CPU architecture:** x86_64
**How docker service was installed:**      
docker-compose file v2

## Command used to create docker container (run/create/compose/screenshot)

bazarr.yaml:

```
---
version: "2"
services:
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1006
      - PGID=1006
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /docker/bazarr/config:/config
      - /mnt/netdata/download/movies:/movies
      - /mnt/netdata/download/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
```
$ docker-compose -f bazarr.yaml up -d
$ mkdir -p /docker/bazarr/config/log && chown 1006:1006 /docker/bazarr/config/log
$ docker inspect -f '{{ index .Config.Labels "build_version" }}' linuxserver/bazarr
Linuxserver.io version:- v0.8.3-ls56 Build-date:- 2019-11-05T12:19:26+00:00

## Docker logs

As per above

**Comment by j0nnymoe** [comment]
Try setting `/config` to `/home/username/appdata/bazarr` and let me know how you get on. Sounds like permissions issues with it using `/dockerdata`

**Comment by esticle** [comment]
Unfortunately not permissions.

I've exposed port 6768 _as_well in the example below and executed it within the container as root and using /tmp:

```
root@8fc0bb7b95fc:/# mkdir /tmp/test
root@8fc0bb7b95fc:/# /usr/bin/python -u /app/bazarr/bazarr/main.py --no-update --config /tmp/test -p6768
Traceback (most recent call last):
  File "/app/bazarr/bazarr/main.py", line 31, in <module>
    configure_logging(settings.general.getboolean('debug') or args.debug)
  File "/app/bazarr/bazarr/logger.py", line 64, in configure_logging
    backupCount=7)
  File "/usr/lib/python2.7/logging/handlers.py", line 171, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 920, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 950, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/tmp/test/log/bazarr.log'
root@8fc0bb7b95fc:/# mkdir /tmp/test/log
root@8fc0bb7b95fc:/# /usr/bin/python -u /app/bazarr/bazarr/main.py --no-update --config /tmp/test -p6768
2019-11-06 14:07:27,890 - root                             (7fb5ad512d48) :  INFO (init:70) - BAZARR Database created successfully
2019-11-06 14:08:10,145 - root                             (7fb5ad512d48) :  INFO (main:2128) - BAZARR is started and waiting for request on http://0.0.0.0:6768/
```
Then visiting the wizard:

```
$ docker exec -it bazarr curl http://localhost:6768/wizard

    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 500 Internal Server Error</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 500 Internal Server Error</h1>
            <p>Sorry, the requested URL <tt>&#039;http://localhost:6768/wizard&#039;</tt>
               caused an error:</p>
            <pre>Internal Server Error</pre>
              <h2>Exception:</h2>
              <pre>AttributeError(&quot;&#039;dict&#039; object has no attribute &#039;code2&#039;&quot;,)</pre>
              <h2>Traceback:</h2>
              <pre>Traceback (most recent call last):
  File &quot;/app/bazarr/bazarr/../libs/bottle.py&quot;, line 862, in _handle
    return route.call(**args)
  File &quot;/app/bazarr/bazarr/../libs/bottle.py&quot;, line 1740, in wrapper
    rv = callback(*a, **ka)
  File &quot;/app/bazarr/bazarr/main.py&quot;, line 122, in wrapper
    return func(*a, **ka)
  File &quot;/app/bazarr/bazarr/main.py&quot;, line 220, in wizard
    base_url=base_url)
  File &quot;/app/bazarr/bazarr/../libs/bottle.py&quot;, line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File &quot;/app/bazarr/bazarr/../libs/bottle.py&quot;, line 3409, in render
    self.execute(stdout, env)
  File &quot;/app/bazarr/bazarr/../libs/bottle.py&quot;, line 3396, in execute
    eval(self.co, env)
  File &quot;/app/bazarr/views/wizard.tpl&quot;, line 114, in &lt;module&gt;
    % include(&#039;wizard_subtitles&#039;)
  File &quot;/app/bazarr/bazarr/../libs/bottle.py&quot;, line 3386, in _include
    return self.cache[_name].execute(env[&#039;_stdout&#039;], env)
  File &quot;/app/bazarr/bazarr/../libs/bottle.py&quot;, line 3396, in execute
    eval(self.co, env)
  File &quot;/app/bazarr/views/wizard_subtitles.tpl&quot;, line 108, in &lt;module&gt;
    &lt;option value=&quot;{{language.code2}}&quot;&gt;{{language.name}}&lt;/option&gt;
AttributeError: &#039;dict&#039; object has no attribute &#039;code2&#039;
</pre>
        </body>
    </html>

```

And the console of course gives the same:

```
Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 122, in wrapper
    return func(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 220, in wizard
    base_url=base_url)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/app/bazarr/views/wizard.tpl", line 114, in <module>
    % include('wizard_subtitles')
  File "/app/bazarr/bazarr/../libs/bottle.py", line 3386, in _include
    return self.cache[_name].execute(env['_stdout'], env)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/app/bazarr/views/wizard_subtitles.tpl", line 108, in <module>
    <option value="{{language.code2}}">{{language.name}}</option>
AttributeError: 'dict' object has no attribute 'code2'
```

**Comment by esticle** [comment]
Ok, figured it out:
* Tag  v0.8.3-ls56 has this issue - where /config/log does not get created and the above dict errors occurs
* Tag v0.8.3.1-ls56 appears to fix this issue, i.e I assume upstream fix.

**Comment by j0nnymoe** [comment]
Glad you got this working :)
