### ISSUE TITLE
Python 3.9.x is unsuported ??

### ISSUE THREAD

**Issue by ptv1p3r** [linuxserver/docker-bazarr#82]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Current Behavior
2021-10-26 14:58:32,547 - root                             (ffffad8b07d0) :  INFO (server:37) - BAZARR is started and waiting for request on http://0.0.0.0:6767
2021-10-26 14:58:32,550 - root                             (ffffa73ab9d0) :  INFO (signalr_client:41) - BAZARR trying to connect to Sonarr SignalR feed...
2021-10-26 14:58:32,567 - root                             (ffffa73abbf0) :  INFO (signalr_client:105) - BAZARR trying to connect to Radarr SignalR feed...
2021-10-26 14:58:32,741 - root                             (ffffa73abae0) :  INFO (signalr_client:129) - BAZARR SignalR client for Radarr is connected and waiting for events.
2021-10-26 14:58:32,915 - root                             (ffffa73ab9d0) :  INFO (signalr_client:56) - BAZARR SignalR client for Sonarr is connected and waiting for events.
Python 3.9.x is unsupported. Current version is 3.9.5. Keep in mind that even if it works, you're on your own.
Bazarr starting...

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
arm64

**How docker service was installed:**
from official docker repo using portainer

## Command used to create docker container (run/create/compose/screenshot)
![image](https://user-images.githubusercontent.com/10048793/139252689-676f6a49-4044-4815-b6d8-c5c1f6b09482.png)

## Docker logs
2021-10-26 14:58:32,547 - root                             (ffffad8b07d0) :  INFO (server:37) - BAZARR is started and waiting for request on http://0.0.0.0:6767
2021-10-26 14:58:32,550 - root                             (ffffa73ab9d0) :  INFO (signalr_client:41) - BAZARR trying to connect to Sonarr SignalR feed...
2021-10-26 14:58:32,567 - root                             (ffffa73abbf0) :  INFO (signalr_client:105) - BAZARR trying to connect to Radarr SignalR feed...
2021-10-26 14:58:32,741 - root                             (ffffa73abae0) :  INFO (signalr_client:129) - BAZARR SignalR client for Radarr is connected and waiting for events.
2021-10-26 14:58:32,915 - root                             (ffffa73ab9d0) :  INFO (signalr_client:56) - BAZARR SignalR client for Sonarr is connected and waiting for events.
Python 3.9.x is unsupported. Current version is 3.9.5. Keep in mind that even if it works, you're on your own.
Bazarr starting...

**Comment by moreje** [comment]
hello, I have exactly the same issue:
`Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/main.py", line 37, in <module>

    from server import app, webserver

  File "/app/bazarr/bin/bazarr/server.py", line 78, in <module>

    webserver = Server()

  File "/app/bazarr/bin/bazarr/server.py", line 29, in __init__

    self.server = create_server(app,

  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 78, in create_server

    last_serv = TcpWSGIServer(

  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 244, in __init__

    self.bind_server_socket()

  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 361, in bind_server_socket

    self.bind(sockaddr)

  File "/app/bazarr/bin/bazarr/../libs/waitress/wasyncore.py", line 396, in bind

    return self.socket.bind(addr)

OSError: [Errno 99] Address not available

Python 3.9.x is unsupported. Current version is 3.9.5. Keep in mind that even if it works, you're on your own.

Bazarr starting...

Bazarr exited.

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/main.py", line 37, in <module>

    from server import app, webserver

  File "/app/bazarr/bin/bazarr/server.py", line 78, in <module>

    webserver = Server()

  File "/app/bazarr/bin/bazarr/server.py", line 29, in __init__

    self.server = create_server(app,

  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 78, in create_server

    last_serv = TcpWSGIServer(

  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 244, in __init__

    self.bind_server_socket()

  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 361, in bind_server_socket

    self.bind(sockaddr)

  File "/app/bazarr/bin/bazarr/../libs/waitress/wasyncore.py", line 396, in bind

    return self.socket.bind(addr)

OSError: [Errno 99] Address not available

Python 3.9.x is unsupported. Current version is 3.9.5. Keep in mind that even if it works, you're on your own.

Bazarr starting...

Bazarr exited.`

**Comment by j0nnymoe** [comment]
post your docker-compose and full docker log

**Comment by kavemang** [comment]
after the latest watchtower update for bazarr I'm seeing bazarr using a lot of resources while the logs for the container state that it has exited and it is unreachable on its port, the error it gives matches this issue, very ... bizarre

**Comment by thelamer** [comment]
This was fixed upstream <https://github.com/morpheus65535/bazarr/blob/e305aad597e67f8da5cfd298ce6039e8e59642ef/bazarr.py#L24>
