### ISSUE TITLE
Web UI Fails with TZ entry

### ISSUE THREAD

**Issue by ssolomon-tech** [linuxserver/docker-bazarr#89]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Should be able to access Web UI with IP:6767

## Current Behavior
Web UI fails to open.

## Steps to Reproduce

1. Removed and redeployed container but same result
2. Removing ENV TZ entry fixes issue
3.
4.

## Environment
**OS:** Ununtu Server 20.04 (Running on Proxmox host)
**CPU architecture:** x86_64
**How docker service was installed:** official docker repo
 

## Command used to create docker container (run/create/compose/screenshot)

version: "2.1"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    network_mode: "container:expressvpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New York
    volumes:
      - /home/ssolomon/appdata/bazarr/config:/config
      - /mnt/PlexMedia/Movies:/movies #optional
      - /mnt/PlexMedia/TV Shows:/tv #optional
    restart: unless-stopped

## Docker logs

    from scheduler import scheduler
  File "/app/bazarr/bin/bazarr/scheduler.py", line 282, in <module>
    scheduler = Scheduler()
  File "/app/bazarr/bin/bazarr/scheduler.py", line 37, in __init__
    self.aps_scheduler = BackgroundScheduler()
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/base.py", line 87, in __init__
    self.configure(gconfig, **options)
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/base.py", line 131, in configure
    self._configure(config)
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/background.py", line 29, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/base.py", line 702, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/app/bazarr/bin/bazarr/../libs/tzlocal/unix.py", line 203, in get_localzone
    _cache_tz = _get_localzone()
  File "/app/bazarr/bin/bazarr/../libs/tzlocal/unix.py", line 161, in _get_localzone
    tzenv = utils._tz_from_env()
  File "/app/bazarr/bin/bazarr/../libs/tzlocal/utils.py", line 122, in _tz_from_env
    raise ZoneInfoNotFoundError(
tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like %s. \nPlease use a timezone in the form of Continent/City'
Bazarr exited.
Bazarr starting...
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 34, in <module>
    from signalr_client import sonarr_signalr_client, radarr_signalr_client  # noqa E402
  File "/app/bazarr/bin/bazarr/signalr_client.py", line 17, in <module>
    from scheduler import scheduler
  File "/app/bazarr/bin/bazarr/scheduler.py", line 282, in <module>
    scheduler = Scheduler()
  File "/app/bazarr/bin/bazarr/scheduler.py", line 37, in __init__
    self.aps_scheduler = BackgroundScheduler()
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/base.py", line 87, in __init__
    self.configure(gconfig, **options)
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/base.py", line 131, in configure
    self._configure(config)
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/background.py", line 29, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/base.py", line 702, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/app/bazarr/bin/bazarr/../libs/tzlocal/unix.py", line 203, in get_localzone
    _cache_tz = _get_localzone()
  File "/app/bazarr/bin/bazarr/../libs/tzlocal/unix.py", line 161, in _get_localzone
    tzenv = utils._tz_from_env()
  File "/app/bazarr/bin/bazarr/../libs/tzlocal/utils.py", line 122, in _tz_from_env
    raise ZoneInfoNotFoundError(
tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like %s. \nPlease use a timezone in the form of Continent/City'
Bazarr exited.
Bazarr starting...
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 34, in <module>
    from signalr_client import sonarr_signalr_client, radarr_signalr_client  # noqa E402
  File "/app/bazarr/bin/bazarr/signalr_client.py", line 17, in <module>
    from scheduler import scheduler
  File "/app/bazarr/bin/bazarr/scheduler.py", line 282, in <module>
    scheduler = Scheduler()
  File "/app/bazarr/bin/bazarr/scheduler.py", line 37, in __init__
    self.aps_scheduler = BackgroundScheduler()
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/base.py", line 87, in __init__
    self.configure(gconfig, **options)
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/base.py", line 131, in configure
    self._configure(config)
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/background.py", line 29, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/base.py", line 702, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/app/bazarr/bin/bazarr/../libs/tzlocal/unix.py", line 203, in get_localzone
    _cache_tz = _get_localzone()
  File "/app/bazarr/bin/bazarr/../libs/tzlocal/unix.py", line 161, in _get_localzone
    tzenv = utils._tz_from_env()
  File "/app/bazarr/bin/bazarr/../libs/tzlocal/utils.py", line 122, in _tz_from_env
    raise ZoneInfoNotFoundError(
tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like %s. \nPlease use a timezone in the form of Continent/City'
Bazarr exited.
Bazarr starting...
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 34, in <module>
    from signalr_client import sonarr_signalr_client, radarr_signalr_client  # noqa E402
  File "/app/bazarr/bin/bazarr/signalr_client.py", line 17, in <module>
    from scheduler import scheduler
  File "/app/bazarr/bin/bazarr/scheduler.py", line 282, in <module>
    scheduler = Scheduler()
  File "/app/bazarr/bin/bazarr/scheduler.py", line 37, in __init__
    self.aps_scheduler = BackgroundScheduler()
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/base.py", line 87, in __init__
    self.configure(gconfig, **options)
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/base.py", line 131, in configure
    self._configure(config)
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/background.py", line 29, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/schedulers/base.py", line 702, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/app/bazarr/bin/bazarr/../libs/tzlocal/unix.py", line 203, in get_localzone
    _cache_tz = _get_localzone()
  File "/app/bazarr/bin/bazarr/../libs/tzlocal/unix.py", line 161, in _get_localzone
    tzenv = utils._tz_from_env()
  File "/app/bazarr/bin/bazarr/../libs/tzlocal/utils.py", line 122, in _tz_from_env
    raise ZoneInfoNotFoundError(
tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like %s. \nPlease use a timezone in the form of Continent/City'
Bazarr exited.
Bazarr starting...

**Comment by j0nnymoe** [comment]
`America/New York` in incorrect, it's `America/New_York`

**Comment by ssolomon-tech** [comment]
> `America/New York` in incorrect, it's `America/New_York`

In using other containers like Sonarr/Radarr I used the syntax of "America/New York" and it worked. Is the TZ naming convention container specific or is there a reaon those work with that syntax and this does not?

**Comment by j0nnymoe** [comment]
Probably more the fact sonarr and radarr are just ignoring it and continuing to load. Bazarr doesn't work like that.
For it to be correct, you need the `_`:
![image](https://user-images.githubusercontent.com/10374553/160239554-ea593fa8-5cc3-43cf-baca-35e2ff0ba686.png)

**Comment by ssolomon-tech** [comment]
> Probably more the fact sonarr and radarr are just ignoring it and continuing to load. Bazarr doesn't work like that. For it to be correct, you need the `_`: ![image](https://user-images.githubusercontent.com/10374553/160239554-ea593fa8-5cc3-43cf-baca-35e2ff0ba686.png)

So besides feeling like an idiot, should I go back and modify the other containers?

**Comment by j0nnymoe** [comment]
Yea it would be worth doing at some point.

**Comment by ssolomon-tech** [comment]
Thanks. I should be able to just edit the container and modify the ENV entry right?

**Comment by j0nnymoe** [comment]
Adjust the TZ entry and assuming you've used compose `docker-compose up -d` and it will rebuild the container.

**Comment by ssolomon-tech** [comment]
Using Portainer so have been doing my edits there.

**Comment by biggt** [comment]
I can confirm that even when utilizing `- TZ=America\New_York`, it is still failing with the same errors that this issue was opened with. 

If I comment out the timezone as I have it configured, it works properly and starts bazarr. 

```
version: "3"
services:
    bazarr:
        image: ghcr.io/linuxserver/bazarr
        container_name: bazarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America\New_York
        volumes:
            - ./config:/config
            - /R6Data/VideoCollection/Movies/HD:/R6Data/VideoCollection/Movies/HD
            - /R6Data/VideoCollection/Movies/4K:/R6Data/VideoCollection/Movies/4K
            - /R6Data/VideoCollection/TVShows:/R6Data/VideoCollection/TVShows
        ports:
            - 6767:6767
        restart: unless-stopped


networks:
    default:
        external:
            name: proxy

```

**Comment by j0nnymoe** [comment]
@biggt because you did `America\New_York` not `America/New_York`.

**Comment by m1dnight** [comment]
I'm having the same issue, but with `Europe/Brussels`. No clue why it doesnt seem to work.

```zoneinfo._common.ZoneInfoNotFoundError: "tzlocal() does not support non-zoneinfo timezones like 'Europe/Brussels'. \nPlease use a timezone in the form of Continent/City"```
