### ISSUE TITLE
Bazarr docker not working

### ISSUE THREAD

**Issue by pravardhanreddy** [linuxserver/docker-bazarr#90]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Access bazarr on port 6767

## Current Behavior

Portainer shows errors and the container keeps restarting

## Steps to Reproduce

1. Configure docker-compose as detailed on the site
2. Start the container

## Environment
**OS:** Debian 10(buster)
**CPU architecture:** x86_64
**How docker service was installed:** Official docker

## Command used to create docker container (run/create/compose/screenshot)

```
---
version: "2.1"
services:
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./config:/config
      - /mnt:/mnt
    network_mode: bridge
    ports:
      - 6767:6767
    restart: unless-stopped
```

## Docker logs

```
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/http.py", line 366, in patched_create_connection
    return _orig_create_connection((host, port), *args, **kwargs)
  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f0db45d2a30>: Failed to establish a new connection: [Errno -3] Try again
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.cognitive.microsofttranslator.com', port=443): Max retries exceeded with url: /languages?api-version=3.0&scope=translation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0db45d2a30>: Failed to establish a new connection: [Errno -3] Try again'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 20, in <module>
    from init import *  # noqa E402
  File "/app/bazarr/bin/bazarr/init.py", line 211, in <module>
    init_binaries()
  File "/app/bazarr/bin/bazarr/init.py", line 192, in init_binaries
    from utils import get_binary
  File "/app/bazarr/bin/bazarr/utils.py", line 27, in <module>
    from deep_translator import GoogleTranslator
  File "/app/bazarr/bin/bazarr/../libs/deep_translator/__init__.py", line 3, in <module>
    from .google_trans import GoogleTranslator
  File "/app/bazarr/bin/bazarr/../libs/deep_translator/google_trans.py", line 5, in <module>
    from .constants import BASE_URLS, GOOGLE_LANGUAGES_TO_CODES, GOOGLE_LANGUAGES_SECONDARY_NAMES
  File "/app/bazarr/bin/bazarr/../libs/deep_translator/constants.py", line 205, in <module>
    microsoft_languages_response = requests.get(microsoft_languages_api_url)
  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.cognitive.microsofttranslator.com', port=443): Max retries exceeded with url: /languages?api-version=3.0&scope=translation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0db45d2a30>: Failed to establish a new connection: [Errno -3] Try again'))
Bazarr starting...
Bazarr exited.
```

**Comment by j0nnymoe** [comment]
Do you have all your other containers pointing to the same config folder by any chance?

**Comment by j0nnymoe** [comment]
also, you dont need the network mode there.

**Comment by pravardhanreddy** [comment]
Hi I have my config folder under `/docker/bazarr/config` and it is empty.

I added the network mode coz I don't want docker creating separate networks for each service.

**Comment by aptalca** [comment]
Config folder should not be empty. It suggests the folder is not set correctly.

Always use absolute paths in compose yaml, not relative ones

**Comment by pravardhanreddy** [comment]
Sorry for the confusion, I meant it was empty before running the container. After I run it, `config db` etc show up. I tried with absolute path and still the same error.

**Comment by pravardhanreddy** [comment]
I deleted everything and tried to start from scratch. This is the log I get now (noticed that there's a new github connection error)

```
Bazarr starting...
Bazarr exited.
2022-03-31 23:43:57,546 - root                             (7f6d4c3e8b48) :  ERROR (check_update:26) - Error trying to get releases from Github. Connection Error.
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/http.py", line 366, in patched_create_connection
    return _orig_create_connection((host, port), *args, **kwargs)
  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f6d46a32430>: Failed to establish a new connection: [Errno -3] Try again
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.cognitive.microsofttranslator.com', port=443): Max retries exceeded with url: /languages?api-version=3.0&scope=translation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6d46a32430>: Failed to establish a new connection: [Errno -3] Try again'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 20, in <module>
    from init import *  # noqa E402
  File "/app/bazarr/bin/bazarr/init.py", line 211, in <module>
    init_binaries()
  File "/app/bazarr/bin/bazarr/init.py", line 192, in init_binaries
    from utils import get_binary
  File "/app/bazarr/bin/bazarr/utils.py", line 27, in <module>
    from deep_translator import GoogleTranslator
  File "/app/bazarr/bin/bazarr/../libs/deep_translator/__init__.py", line 3, in <module>
    from .google_trans import GoogleTranslator
  File "/app/bazarr/bin/bazarr/../libs/deep_translator/google_trans.py", line 5, in <module>
    from .constants import BASE_URLS, GOOGLE_LANGUAGES_TO_CODES, GOOGLE_LANGUAGES_SECONDARY_NAMES
  File "/app/bazarr/bin/bazarr/../libs/deep_translator/constants.py", line 205, in <module>
    microsoft_languages_response = requests.get(microsoft_languages_api_url)
  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.cognitive.microsofttranslator.com', port=443): Max retries exceeded with url: /languages?api-version=3.0&scope=translation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6d46a32430>: Failed to establish a new connection: [Errno -3] Try again'))
Bazarr starting...
Bazarr exited.
```

**Comment by j0nnymoe** [comment]
That would imply a networking issue on your host. Or I have seen an incorrect TZ cause the same issue.

**Comment by pravardhanreddy** [comment]
Ok, I think it might be because of pihole. I recently moved my pihole installation to docker and some searches online seem to indicate that there is some issue where other containers are unable to perform DNS lookup. I will look into solving that part first and will report back. Thanks for the help. I will close the issue. I also think it might be better if the container at least starts even if the lookup fails so it's easier to circle in on the issue. Cheers.

**Comment by j0nnymoe** [comment]
It's not us that stops the container from starting, it's bazarr itself, out of our control.

**Comment by pravardhanreddy** [comment]
Gotcha. Thanks
